export const SHOW_LOADING_MODAL = 'SHOW_LOADING_MODAL'
export const HIDE_LOADING_MODAL = 'HIDE_LOADING_MODAL'

export const SHOW_ERROR_ALERT = 'SHOW_ERROR_ALERT'
export const HIDE_ERROR_ALERT = 'HIDE_ERROR_ALERT'
