export const SHOW_POST_COMPONENTS_SELECTOR_MODAL =
  "SHOW_POST_COMPONENTS_SELECTOR_MODAL";
export const HIDE_POST_COMPONENTS_SELECTOR_MODAL =
  "HIDE_POST_COMPONENTS_SELECTOR_MODAL";

export const SHOW_ADD_POST_COMPONENT_MODAL = "SHOW_ADD_POST_COMPONENT_MODAL";
export const HIDE_ADD_POST_COMPONENT_MODAL = "HIDE_ADD_POST_COMPONENT_MODAL";
