export const SHOW_POST_COMPONENTS_SELECTOR_MODAL =
  "SHOW_POST_COMPONENTS_SELECTOR_MODAL";
export const HIDE_POST_COMPONENTS_SELECTOR_MODAL =
  "HIDE_POST_COMPONENTS_SELECTOR_MODAL";

export const SHOW_ADD_POST_COMPONENT_MODAL = "SHOW_ADD_POST_COMPONENT_MODAL";
export const HIDE_ADD_POST_COMPONENT_MODAL = "HIDE_ADD_POST_COMPONENT_MODAL";

export const INITIALIZE_POST_TO_EDIT = "INITIALIZE_POST_TO_EDIT";
export const REMOVE_COMPONENT = "REMOVE_COMPONENT";
export const ADD_COMPONENT = "ADD_COMPONENT";
export const RESET_POST = "RESET_POST";
